# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4777b6942c77812933eb57528c7b571feffbbcd133dc9b691bb3281f1a8269397ff847ceade5d652d570dc3e8d6b940b990c8aa497d4282ada3a14015f4faa23

test:
  secret_key_base: 0c109276a8fb548091e5f2baa56c8b98d1be8cffa9d5382937d8fa8d15ab53752acd8194416fd3adf4b2da17c1432404ea7ae1e6415da3ba7ce471e24e9e2be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
